
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/DoAn3
        username: postgres
        password: 418888
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: smtp.gmail.com
        port: 587
        username: "khangnguyen41888@gmail.com"
        password: "kato nmzx vfft mhcu"
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    security:
        oauth2:
            client:
                registration:
                            google:
                                client-id: "547597069622-g63m24j838unu54rlmblubc89ba2bq9u.apps.googleusercontent.com"
                                client-secret: "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"
                                scope: email,profile
                                redirect-uri: "http://localhost:8080/login/oauth2/code/google"
                provider:
                            google:
                                authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth"
                                token-uri: "https://oauth2.googleapis.com/token"
                                user-info-uri: "https://openidconnect.googleapis.com/v1/userinfo"
                                user-name-attribute: name
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
            enabled: true

gemini:
    api-key: "AIzaSyBPIe6kQjz5JsKz3qh_p57b9_ulRTjtjHU"
    model: "gemini-2.5-pro"
    base-url: "https://generativelanguage.googleapis.com/v1beta/models"

ai:
    chatbot:
        enabled: true
        max-tokens: 250
        rag:
            top-k: 5
            similarity-threshold: 0.6

tour:
    detail:
        base-url: "http://localhost:8080/Client/TourDetail/"

promotion:
    detail:
        base-url: "http://localhost:8080/Client/khuyen-mai/"

